User can search for movie titles
OSAdams/Movie-Review pull request #11
Opened 2021-04-10 01:37 UTC by OSAdams

2021-04-11 00:53 UTC, thebearingedge requested changes

2021-04-11 00:53 UTC, thebearingedge commented on client/pages/home.jsx
> +        console.log(movieObj);
we don't "kick variables out" of a fetch chain like this.

2021-04-11 00:53 UTC, thebearingedge commented on server/public/index.html
> +  <link rel="preconnect" href="https://fonts.gstatic.com">
this is in here twice.

2021-04-12 17:27 UTC, OSAdams commented
![image](https://user-images.githubusercontent.com/76730244/114436026-dff77880-9b92-11eb-8b19-5a26cf3efadd.png)

2021-04-12 17:37 UTC, thebearingedge approved these changes

2021-04-12 17:41 UTC, merged